//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsZoo.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal_Material
    {
        public int Id { get; set; }
        public int Animal_Id { get; set; }
        public int Material_Id { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual CareMaterial CareMaterial { get; set; }
    }
}
