//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsZoo.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Animal_Material = new HashSet<Animal_Material>();
            this.Animal_Product = new HashSet<Animal_Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Aviary_Id { get; set; }
        public int Kind_Id { get; set; }
        public int Condition_Id { get; set; }
    
        public virtual AnimalKind AnimalKind { get; set; }
        public virtual Aviary Aviary { get; set; }
        public virtual ConditionAccommodation ConditionAccommodation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal_Material> Animal_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal_Product> Animal_Product { get; set; }
    }
}
