//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsZoo.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aviary()
        {
            this.Animal = new HashSet<Animal>();
            this.User_Aviary = new HashSet<User_Aviary>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AnimalCount { get; set; }
        public bool Cleaned { get; set; }
        public bool Cooled { get; set; }
        public int Type_Id { get; set; }
        public int Temperature_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animal { get; set; }
        public virtual Temperature Temperature { get; set; }
        public virtual TypeAviary TypeAviary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Aviary> User_Aviary { get; set; }
    }
}
