//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsZoo.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temperature_Method
    {
        public int Id { get; set; }
        public int Temperature_Id { get; set; }
        public int Method_Id { get; set; }
    
        public virtual CoolingMethod CoolingMethod { get; set; }
        public virtual Temperature Temperature { get; set; }
    }
}
