//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsZoo.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Aviary
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Aviary_Id { get; set; }
    
        public virtual Aviary Aviary { get; set; }
        public virtual User User { get; set; }
    }
}
