//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsZoo.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalsZooEntities : DbContext
    {
        public AnimalsZooEntities()
            : base("name=AnimalsZooEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Animal_Material> Animal_Material { get; set; }
        public virtual DbSet<Animal_Product> Animal_Product { get; set; }
        public virtual DbSet<AnimalKind> AnimalKind { get; set; }
        public virtual DbSet<Aviary> Aviary { get; set; }
        public virtual DbSet<CareMaterial> CareMaterial { get; set; }
        public virtual DbSet<ConditionAccommodation> ConditionAccommodation { get; set; }
        public virtual DbSet<CoolingMethod> CoolingMethod { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Temperature> Temperature { get; set; }
        public virtual DbSet<Temperature_Method> Temperature_Method { get; set; }
        public virtual DbSet<TypeAviary> TypeAviary { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_Aviary> User_Aviary { get; set; }
    }
}
