//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public int Id { get; set; }
        public System.DateTime DiseaseDate { get; set; }
        public System.DateTime RecoveryDate { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public int TreatmentId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
